### ISSUE TITLE
Monthly payment dates are incorrect

### ISSUE THREAD

**Issue by jerryjohnjacob** [geona-george/calculator.github.io#1]
Only the first monthly payment is correct. After that, the rest of the dates are all the same and are not right.

<img width="499" alt="Screenshot 2020-11-12 at 2 06 01 PM" src="https://user-images.githubusercontent.com/4962432/98915736-4d25b580-24f0-11eb-98d9-6115024a619e.png">

**Comment by geona-george** [comment]
okay, sir. I got it. Are there any other issues that I have to look into? And sir I know it was a task given to me and I tried many ways but couldn't increment the dates . Apart from getting selected for the next round or not, can you please suggest to me a method or way to get the right dates? I'm asking you this because If you help me, it will improve my knowledge and will help me to do better in the future.  Thank you sir for sharing the issue.

**Comment by jerryjohnjacob** [comment]
Try looking into [this](https://momentjs.com/)

**Comment by geona-george** [comment]
Thank you, sir. I will look into it and try it, I will do the corrections and push it in the GitHub.

**Comment by geona-george** [comment]
sir, I have corrected the dates. Please check into it.

**Comment by jerryjohnjacob** [comment]
Looks good! Nice work.
